spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: test
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: blue
---
spring:
  config:
    activate:
      on-profile: green